services:
  target12:
    image: 'ubuntu-target:v1'
    container_name: 'target12'
    networks:
      jenkins-ansible-docker_jadoc_net:
        ipv4_address: 172.19.0.12

  target13:
    image: 'ubuntu-target:v1'
    container_name: 'target13'
    networks:
      jenkins-ansible-docker_jadoc_net:
        ipv4_address: 172.19.0.13

  target14:
    image: 'ubuntu-target:v1'
    container_name: 'target14'
    networks:
      jenkins-ansible-docker_jadoc_net:
        ipv4_address: 172.19.0.14

networks:
  jenkins-ansible-docker_jadoc_net:
    external: true
